<div id="breadcrumb" class="container">
    <nav class="breadcrumb is-centered has-bullet-separator">
        <ul>
            <li id="article-new"><a href="/admin/article/new">New</a></li>
            <li id="article-list"><a href="/admin/article/list">Articles</a></li>
            <li id="upload"><a>Upload</a></li>
            <li id="update-password"><a>Update Password</a></li>
        </ul>
    </nav>
</div>