<#macro header title>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>${title}</title>
        <link rel="preconnect" href="https://cdn.jsdelivr.net">
        <link href="https://cdn.jsdelivr.net/npm/fomantic-ui/dist/semantic.min.css" rel="stylesheet">
        <link href="/css/backend.css" rel="stylesheet">
        <#nested>
    </head>
</#macro>